services:
  - type: web
    name: editresume-backend
    dockerfilePath: ./Dockerfile.render
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: editresume-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: OPENAI_MAX_TOKENS
        value: "2000"
      - key: PREMIUM_MODE
        value: "false"
      - key: ENVIRONMENT
        value: "staging"
      - key: PYTHONPATH
        value: "/opt/render/project/src"

